stages:
  process_data:
    cmd: python scripts/process_data.py
    deps:
      - scripts/process_data.py
      - data/raw/iris.csv
    outs:
      - processed_data/stock_data.parquet

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - processed_data/stock_data.parquet
      - feature_repo/features.py
      - feature_repo/feature_store.yaml
    outs:
      - models/best_model.pkl
